//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public string Batch_Id { get; set; }
        public string Starting_Year { get; set; }
        public string Ending_Year { get; set; }
        public string Department_Id { get; set; }
        public string Status { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
