//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Batches = new HashSet<Batch>();
            this.Exams = new HashSet<Exam>();
            this.Users = new HashSet<User>();
        }
    
        public string Department_Id { get; set; }
    
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
