//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freeze
    {
        public string Student_Id { get; set; }
        public Nullable<System.DateTime> Freezing_Date { get; set; }
        public Nullable<System.DateTime> Unfreezing_Date { get; set; }
        public string Status { get; set; }
    }
}
