//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FYP_DB_Entities : DbContext
    {
        public FYP_DB_Entities()
            : base("name=FYP_DB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Batch> Batches { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Drop_Out> Drop_Out { get; set; }
        public DbSet<Enrolled> Enrolleds { get; set; }
        public DbSet<Exam> Exams { get; set; }
        public DbSet<Freeze> Freezes { get; set; }
        public DbSet<Option> Options { get; set; }
        public DbSet<Paper> Papers { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<Result> Results { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
