//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Options = new HashSet<Option>();
            this.Papers = new HashSet<Paper>();
        }
    
        public int Question_Id { get; set; }
        public string Questions { get; set; }
        public string Subject_Id { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Option> Options { get; set; }
        public virtual ICollection<Paper> Papers { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
