//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Schedule_Id { get; set; }
        public string Room_Id { get; set; }
        public Nullable<int> Exam_Id { get; set; }
        public Nullable<System.DateTime> Time_From { get; set; }
        public Nullable<System.DateTime> Time_To { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Room Room { get; set; }
    }
}
